### ISSUE TITLE
mobile vs desktop difference: plot x axes 

### ISSUE THREAD

**Issue by ArielleEagan** [rohandandavati/rohandandavati.github.io#67]
Mobile version shortens the x axes differently across plots. Ex: On the mobile version, "Transmission Status" plot axis starts in April (followed by Jul, Oct, Jan). All other plots have labels starting in May (followed by Jul, Sep, Nov, Jan). Screenshot below. On the desktop, all plot x axes begin in March, with labels consistent (monthly from Apr to Jan). 
![IMG_20EE4C1B6589-1](https://user-images.githubusercontent.com/72713772/104762594-3c7d0000-572a-11eb-841c-e68073c91118.jpeg)

**Comment by samhovie** [comment]
227b3531b0dc577307c24fb26111c0487b182e25
