### ISSUE TITLE
mobile version: map covering drop down menu

### ISSUE THREAD

**Issue by ArielleEagan** [rohandandavati/rohandandavati.github.io#76]
clicking on drop down icon (top right, 3 horizontal bars) gives options on left that are covered by the IL map (see images attached)
![IMG_0500](https://user-images.githubusercontent.com/72713772/105071986-e7ebc480-5a4a-11eb-8a68-37470e73f3b7.PNG)
![IMG_0499](https://user-images.githubusercontent.com/72713772/105071984-e6ba9780-5a4a-11eb-913d-2b2a4cadc346.PNG)

**Comment by samhovie** [comment]
3a229387fb84f08c1c20f261dfc36038a9c88cd4
