### ISSUE TITLE
legend tags on Rt plot overlapping 

### ISSUE THREAD

**Issue by ArielleEagan** [rohandandavati/rohandandavati.github.io#80]
see screenshot attached - legend markers w/disease modeling group name and date overlapping one another so unable to ready clearly 
![image (3)](https://user-images.githubusercontent.com/72713772/106962450-c0605180-6704-11eb-91e2-ced6323f6fdb.png)

**Comment by samhovie** [comment]
1b9a447f6b2018388d6587662fdc23f644f66088
