### ISSUE TITLE
County mouseover text cut off

### ISSUE THREAD

**Issue by philarevalo** [rohandandavati/rohandandavati.github.io#90]
For the northern counties, the mouseover text box gets cut off by the top menu bar. Using Firefox 86.0.

![image](https://user-images.githubusercontent.com/10436689/110480491-29443c00-80ac-11eb-8395-502ba267679a.png)

**Comment by samhovie** [comment]
8a5f88219b33863f2c8e0ef195383fd1fb5ba873
